[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  NPM_FLAGS = "--no-audit --no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 